@@ -44,9 +44,9 @@
 #include "muscle-tab.h"
 #include "nullable.h"
 #include "output.h"
+#include "print-graph.h"
 #include "print-xml.h"
 #include "print.h"
-#include "print_graph.h"
 #include "reader.h"
 #include "reduce.h"
 #include "scan-code.h"
