@@ -1,6 +1,6 @@
 /* Output Graphviz specification of a state machine generated by Bison.
 
-   Copyright (C) 2006 Free Software Foundation, Inc.
+   Copyright (C) 2006, 2007 Free Software Foundation, Inc.
 
    This file is part of Bison, the GNU Compiler Compiler.
 
@@ -38,20 +38,20 @@ quote (char const *name)
 void
 start_graph (FILE *fout)
 {
-  fputs ("digraph Automaton{\n", fout);
+  fputs ("digraph Automaton {\n", fout);
 }
 
 void
 output_node (int id, char const *label, FILE *fout)
 {
-  fprintf (fout, "%d[label=%s]\n", id, quote (label));
+  fprintf (fout, "  %d [label=%s]\n", id, quote (label));
 }
 
 void
 output_edge (int source, int destination, char const *label,
 	     char const *style, FILE *fout)
 {
-  fprintf (fout, "%d->%d[style=%s", source, destination, style);
+  fprintf (fout, "  %d -> %d [style=%s", source, destination, style);
   if (label)
     fprintf (fout, " label=%s", quote (label));
   fputs ("]\n", fout);
