@@ -24,6 +24,7 @@
 
 #include <quotearg.h>
 
+#include "files.h"
 #include "graphviz.h"
 
 /* Return an unambiguous printable representation for NAME, suitable
@@ -38,7 +39,20 @@ quote (char const *name)
 void
 start_graph (FILE *fout)
 {
-  fputs ("digraph Automaton {\n", fout);
+  fprintf (fout,
+           _("/*\n"
+             " * Generated by %s.\n"
+             " * Report bugs to <%s>.\n"
+             " * Home page: <%s>.\n"
+             " */\n"
+             "\n"),
+           PACKAGE_STRING,
+           PACKAGE_BUGREPORT,
+           PACKAGE_URL);
+  fprintf (fout,
+           "digraph %s\n"
+           "{\n",
+           quote (grammar_file));
 }
 
 void
